/* BitlBee settings, generated by configure
   
   Do *NOT* use any of these defines in your code without thinking twice, most
   of them can/will be overridden at run-time */

#define CONFIG "/var/lib/bitlbee/"
#define ETCDIR "/etc/bitlbee/"
#define VARDIR "/usr/share/bitlbee/"
#define PLUGINDIR "/usr/lib/bitlbee/"
#define PIDFILE "/var/run/bitlbee/bitlbee.pid"
#define IPCSOCKET "/var/run/bitlbee/bitlbee.sock"
#define ARCH "Linux"
#define CPU "x86_64"
#define EVENTS_GLIB
#define HAVE_RESOLV_A
#undef WITH_LDAP
#define WITH_PLUGINS
#define OTR_PI
#undef BITLBEE_VERSION
#define BITLBEE_VERSION "bzr-699"
#undef WITH_PURPLE
#undef WITH_MSN
#define WITH_JABBER
#undef WITH_OSCAR
#define WITH_YAHOO
#define WITH_TWITTER
